version: '3'

services:

  apache:
    image: geekzonehostingllc/clipbucket-lamp-server:php74
    container_name: 'apache'
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
    volumes:
      - ./app/upload:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/php.ini
      #- ./docker/vhosts:/etc/apache2/sites-enabled
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
    networks:
      - net 

      
  mysql:
    container_name: "mysql"
    restart: unless-stopped
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --sql_mode=''
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    volumes:
      - data:/var/lib/mysql
      - ./docker/mysql/dump/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    ports:
      - "3306:3306"
    networks:
      - net

  phpmyadmin:
    container_name: "phpmyadmin"
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8080:80"
    networks:
      - net

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - net

volumes:
  data:

networks:
  net:
